ARG OTP_VERSION

FROM docker.io/library/erlang:${OTP_VERSION}
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup user for matching permissions in mounted volumes
ARG USER_UID=1000
ARG USER_GID=1000
RUN groupadd -g ${USER_GID} dev && \
    useradd -m -l -s /bin/bash -u ${USER_UID} -g ${USER_GID} dev
USER $USER_UID

# Set env
ENV CHARSET=UTF-8
ENV LANG=C.UTF-8

# Set runtime
CMD ["/bin/bash"]
